version: '3'

services:
  # MongoDB databases for each service
  auth-db:
    image: mongo:latest
    container_name: auth-db
    volumes:
      - auth-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - property-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  property-db:
    image: mongo:latest
    container_name: property-db
    volumes:
      - property-db-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - property-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  maintenance-db:
    image: mongo:latest
    container_name: maintenance-db
    volumes:
      - maintenance-db-data:/data/db
    ports:
      - "27019:27017"
    networks:
      - property-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  payment-db:
    image: mongo:latest
    container_name: payment-db
    volumes:
      - payment-db-data:/data/db
    ports:
      - "27020:27017"
    networks:
      - property-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword

  # Microservices
  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - auth-db
    networks:
      - property-network
    environment:
      - MONGO_URI=mongodb://root:rootpassword@auth-db:27017/auth?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - PORT=3001

  property-service:
    build: ./property-service
    container_name: property-service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - property-db
      - auth-service
    networks:
      - property-network
    environment:
      - MONGO_URI=mongodb://root:rootpassword@property-db:27017/property?authSource=admin
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PORT=3002

  maintenance-service:
    build: ./maintenance-service
    container_name: maintenance-service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - maintenance-db
      - auth-service
    networks:
      - property-network
    environment:
      - MONGO_URI=mongodb://root:rootpassword@maintenance-db:27017/maintenance?authSource=admin
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PORT=3003

  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - payment-db
      - auth-service
    networks:
      - property-network
    environment:
      - MONGO_URI=mongodb://root:rootpassword@payment-db:27017/payment?authSource=admin
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PORT=3004

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - property-service
      - maintenance-service
      - payment-service
    networks:
      - property-network
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - PROPERTY_SERVICE_URL=http://property-service:3002
      - MAINTENANCE_SERVICE_URL=http://maintenance-service:3003
      - PAYMENT_SERVICE_URL=http://payment-service:3004
      - PORT=3000

networks:
  property-network:
    driver: bridge

volumes:
  auth-db-data:
  property-db-data:
  maintenance-db-data:
  payment-db-data: 